name: Demo to create automatic PR
# This is a basic workflow to help you get started with Actions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
      - sanchit
      - harsh
      - bnav

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  createPullRequest:
    runs-on: ubuntu-latest

    steps:
      - name: checking out code
        uses: actions/checkout@v2

      - name: extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: Update report file
        run: |
          var=$(date)
          var=`date`
          echo "$var" - ${{ env.GIT_COMMIT_MESSAGE_SUBJECT }} >> REPORT.md

      - name: Raise Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "dev"
          base: main
          title: ${{ env.GIT_COMMIT_MESSAGE_SUBJECT }}
          committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          body: ${{ env.GIT_COMMIT_MESSAGE_BODY }}
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: true

      - name: Create or Update Project Card
        uses: peter-evans/create-or-update-project-card@v1
        with:
          project-name: Development
          column-name: To do
          issue-number: ${{ steps.cpr.outputs.pull-request-number }}
